import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";
// import SessionProvider from "~/app/_components/SessionProvider";
// import { getServerAuthSession } from "~/server/auth";
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
import { cn } from "~/lib/utils";

import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable} dark`}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          fontSans.variable,
        )}
      >
        {/* <SessionProvider session={session}> */}
        <TRPCReactProvider>{children}</TRPCReactProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
